// Vedic Lifestyle Diet — master data: SLOTS, CATEGORY, EAT_OUT, ORDER_SEARCH, ORDER_TIPS, ORDER_NOTES, ORDER_CITIES, RULES, GOALS, DAILY.
// Types: veg < egg < nonveg. "light" marks lighter options. "suits" lists doshas (V/P/K) an option is traditionally good for.
const SLOTS = [
  { id: 'wake', label: 'Wake-up', time: '06:45', main: false, options: [
    { name: 'Warm water + 5 soaked peeled almonds', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Almonds'] },
    { name: 'Jeera water (boiled cumin water)', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Cumin'] },
    { name: 'Warm water with a pinch of dry ginger', type: 'veg', light: true, suits: ['V', 'K'], ing: ['Ginger'] },
    { name: 'Soaked raisins + warm water', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Raisins'] },
    { name: 'Warm water + 2 dates', type: 'veg', suits: ['V', 'P'], ing: ['Dates'] },
    { name: 'Tender coconut water', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Tender coconut'] },
  ]},
  { id: 'breakfast', label: 'Breakfast', time: '08:00', main: true, options: [
    { name: '2 boiled eggs + 2 rotis with ghee', type: 'egg', suits: ['V', 'K'], ing: ['Eggs', 'Atta', 'Ghee'] },
    { name: 'Moong dal chilla + banana', type: 'veg', suits: ['P', 'K'], ing: ['Moong dal', 'Banana'] },
    { name: 'Pesarattu with ghee', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Moong dal', 'Ghee'] },
    { name: 'Idli + coconut chutney + ghee', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Idli rice', 'Urad dal', 'Coconut', 'Ghee'] },
    { name: 'Poached eggs + rava upma', type: 'egg', suits: ['V', 'P'], ing: ['Eggs', 'Rava', 'Ghee'] },
    { name: 'Ven pongal with ghee', type: 'veg', light: true, suits: ['V', 'K'], ing: ['Rice', 'Moong dal', 'Ghee', 'Pepper'] },
    { name: 'Rava upma with curry leaves', type: 'veg', suits: ['V', 'P', 'K'], ing: ['Rava', 'Cashews', 'Curry leaves'] },
    { name: 'Ragi malt porridge (warm)', type: 'veg', suits: ['V', 'K'], ing: ['Ragi', 'Milk'] },
    { name: 'Idiyappam + coconut milk vegetable stew', type: 'veg', suits: ['V', 'P'], ing: ['Rice', 'Coconut', 'Coconut milk'] },
    { name: 'Ragi dosa + coconut chutney', type: 'veg', suits: ['P', 'K'], ing: ['Ragi', 'Urad dal', 'Coconut'] },
    { name: 'Aloo paratha with ghee', type: 'veg', suits: ['V'], ing: ['Atta', 'Potato', 'Ghee'] },
    { name: 'Palak paratha with ghee', type: 'veg', suits: ['P', 'K'], ing: ['Atta', 'Palak', 'Ghee'] },
    { name: 'Methi paratha with ghee', type: 'veg', suits: ['V', 'K'], ing: ['Atta', 'Methi', 'Ghee'] },
    { name: 'Oats porridge with dates', type: 'veg', suits: ['V', 'P'], ing: ['Oats', 'Milk', 'Dates'] },
    { name: 'Dalia khichdi with ghee', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Dalia', 'Moong dal', 'Ghee'] },
    { name: 'Foxtail millet upma', type: 'veg', light: true, suits: ['K', 'P'], ing: ['Foxtail millet', 'Carrot', 'Beans'] },
    { name: 'Poha with peanuts and curry leaves', type: 'veg', suits: ['V', 'P'], ing: ['Poha', 'Peanuts', 'Curry leaves'] },
    { name: 'Egg bhurji (mild) + phulka', type: 'egg', suits: ['V', 'K'], ing: ['Eggs', 'Atta', 'Tomato'] },
  ]},
  { id: 'mid', label: 'Mid-morning', time: '11:00', main: false, options: [
    { name: 'Banana or mango + soaked almonds', type: 'veg', suits: ['V', 'P'], ing: ['Banana', 'Almonds'] },
    { name: 'Coconut water + 2 dates', type: 'veg', light: true, suits: ['P', 'K', 'V'], ing: ['Tender coconut', 'Dates'] },
    { name: 'Grapes + soaked raisins', type: 'veg', suits: ['V', 'P', 'K'], ing: ['Grapes', 'Raisins'] },
    { name: 'Buttermilk with curry leaves', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Buttermilk', 'Curry leaves'] },
    { name: 'Roasted chana + jaggery', type: 'veg', suits: ['K', 'V'], ing: ['Roasted chana', 'Jaggery'] },
    { name: 'Fresh pomegranate juice', type: 'veg', light: true, suits: ['P', 'K', 'V'], ing: ['Pomegranate'] },
    { name: 'Sprouted moong + carrot sticks', type: 'veg', light: true, suits: ['K', 'P'], ing: ['Whole moong', 'Carrot'] },
    { name: 'Cucumber sticks', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Cucumber'] },
    { name: 'Handful of walnuts', type: 'veg', suits: ['V'], ing: ['Walnuts'] },
    { name: 'Sweet lime segments', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Sweet lime'] },
  ]},
  { id: 'lunch', label: 'Lunch', time: '13:15', main: true, gymNote: 'Gym day: take an extra helping of rice and dal.', options: [
    { name: 'Rice + dal with ghee + mild chicken curry + cucumber raita + bottle gourd curry', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Toor dal', 'Ghee', 'Desi chicken', 'Cucumber', 'Bottle gourd'], note: 'Traditionally, curd is kept apart from meat and eggs — have the curd at another meal.' },
    { name: 'Rice + chicken stew (coconut) + pappu + beans poriyal + curd', type: 'nonveg', suits: ['V', 'P', 'K'], ing: ['Rice', 'Desi chicken', 'Coconut', 'Moong dal', 'Beans', 'Ghee'], note: 'Traditionally, curd is kept apart from meat and eggs — have the curd at another meal.' },
    { name: 'Rice + pappu with ghee + egg curry + majjiga', type: 'egg', suits: ['V', 'K'], ing: ['Rice', 'Moong dal', 'Ghee', 'Eggs'], note: 'Traditionally, curd is kept apart from meat and eggs — have the curd at another meal.' },
    { name: 'Rice + sambar + paneer curry + sweet potato fry (shallow) + curd', type: 'veg', suits: ['V', 'K'], ing: ['Rice', 'Toor dal', 'Paneer', 'Sweet potato', 'Curd', 'Ghee'] },
    { name: 'Curd rice + pappu + ridge gourd curry', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Rice', 'Curd', 'Moong dal', 'Ridge gourd', 'Ghee'] },
    { name: 'Rice + mild rohu fish curry + beans poriyal', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Rohu fish', 'Beans', 'Coconut'] },
    { name: 'Rice + seer fish (vanjaram) shallow fry + mild tomato side', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Seer fish', 'Pepper', 'Tomato'] },
    { name: 'Rice + mild prawns curry + cabbage poriyal', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Prawns', 'Cabbage', 'Coconut'] },
    { name: 'Rice + mutton curry (desi, mild spice) + carrot poriyal', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Mutton', 'Carrot', 'Onion'] },
    { name: 'Steamed pomfret + rice + dal with ghee', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Pomfret', 'Toor dal', 'Ghee'] },
    { name: 'Desi chicken pepper fry (shallow) + rice + pappu', type: 'nonveg', suits: ['V', 'K'], ing: ['Rice', 'Desi chicken', 'Pepper'] },
    { name: 'Rice + mild tomato egg curry + cucumber salad', type: 'egg', suits: ['V', 'K'], ing: ['Rice', 'Eggs', 'Tomato', 'Coriander'] },
    { name: 'Vegetable pulao + raita + salad', type: 'veg', suits: ['P', 'K'], ing: ['Rice', 'Curd', 'Beans', 'Carrot', 'Ghee'] },
    { name: 'Rice + chana dal kootu (coconut) + beans poriyal + majjiga', type: 'veg', suits: ['P', 'K'], ing: ['Rice', 'Chana dal', 'Coconut', 'Beans', 'Buttermilk'] },
    { name: 'Jowar roti + tomato pappu + bottle gourd curry', type: 'veg', suits: ['V', 'K'], ing: ['Jowar', 'Tomato', 'Toor dal', 'Bottle gourd'] },
    { name: 'Rice + palak pappu + sweet potato fry (shallow) + curd', type: 'veg', suits: ['V', 'P', 'K'], ing: ['Rice', 'Palak', 'Toor dal', 'Sweet potato', 'Curd'] },
    { name: 'Rice + thotakura (amaranth) dal + ridge gourd curry + curd', type: 'veg', suits: ['P', 'K'], ing: ['Rice', 'Thotakura', 'Toor dal', 'Ridge gourd', 'Curd'] },
    { name: 'Foxtail millet pulao + dal + carrot salad', type: 'veg', light: true, suits: ['K', 'P'], ing: ['Foxtail millet', 'Moong dal', 'Carrot', 'Beans'] },
    { name: 'Rice + sambar + raw banana poriyal + curd', type: 'veg', suits: ['V', 'K'], ing: ['Rice', 'Toor dal', 'Raw banana', 'Curd'] },
    { name: 'Rice + methi pappu + beetroot poriyal', type: 'veg', suits: ['V', 'K'], ing: ['Rice', 'Methi', 'Toor dal', 'Beetroot'] },
  ]},
  { id: 'snack', label: 'Evening snack', time: '16:00', main: false, options: [
    { name: 'Warm milk with cardamom', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Milk', 'Cardamom'] },
    { name: 'Roasted makhana in ghee', type: 'veg', suits: ['V', 'P', 'K'], ing: ['Makhana', 'Ghee'] },
    { name: 'Mixed nuts + 2 dates', type: 'veg', suits: ['V', 'P'], ing: ['Almonds', 'Cashews', 'Dates'] },
    { name: 'Roasted peanuts + jaggery', type: 'veg', suits: ['V'], ing: ['Peanuts', 'Jaggery'] },
    { name: 'Sundal (boiled chickpeas, mild)', type: 'veg', suits: ['K', 'P'], ing: ['Chickpeas', 'Coconut', 'Curry leaves'] },
    { name: 'Rava laddu (1 piece)', type: 'veg', suits: ['V'], ing: ['Rava', 'Ghee', 'Jaggery'] },
    { name: 'Steamed corn with a pinch of salt', type: 'veg', suits: ['V', 'K'], ing: ['Corn'] },
    { name: 'Mild masala oats', type: 'veg', suits: ['K', 'V'], ing: ['Oats', 'Carrot', 'Peas'] },
    { name: 'Bajra roti + ghee (small)', type: 'veg', suits: ['V', 'K'], ing: ['Bajra', 'Ghee'] },
    { name: 'Peanut chikki (1 piece)', type: 'veg', suits: ['V'], ing: ['Peanuts', 'Jaggery'] },
    { name: 'Warm badam milk', type: 'veg', suits: ['V', 'P'], ing: ['Milk', 'Almonds', 'Cardamom'] },
    { name: 'Boiled sweet potato cubes with pepper', type: 'veg', suits: ['V', 'K'], ing: ['Sweet potato', 'Pepper'] },
  ]},
  { id: 'postgym', label: 'Post-workout', gymOnly: true, main: false, options: [
    { name: 'Dates + warm milk', type: 'veg', suits: ['V', 'P'], ing: ['Dates', 'Milk'] },
    { name: 'Coconut water + banana', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Tender coconut', 'Banana'] },
    { name: '2 boiled eggs + toast', type: 'egg', suits: ['V', 'K'], ing: ['Eggs', 'Atta'] },
    { name: 'Ragi malt with jaggery', type: 'veg', suits: ['V', 'K'], ing: ['Ragi', 'Milk', 'Jaggery'] },
    { name: 'Almond-date milk', type: 'veg', suits: ['V', 'P'], ing: ['Milk', 'Almonds', 'Dates'] },
    { name: 'Moong dal chilla (2) with ghee', type: 'veg', suits: ['P', 'K'], ing: ['Moong dal', 'Ghee'] },
  ]},
  { id: 'fruit', label: 'Fruit (optional)', time: '18:00', main: false, optional: true, options: [
    { name: 'Sweet fruit (papaya, pear, grapes)', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Papaya', 'Grapes'] },
    { name: 'Coconut water', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Tender coconut'] },
    { name: 'Pomegranate bowl', type: 'veg', light: true, suits: ['P', 'K', 'V'], ing: ['Pomegranate'] },
    { name: 'Ripe sweet mango (in season)', type: 'veg', suits: ['V', 'P'], ing: ['Mango'] },
    { name: 'Grapes + pear', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Grapes', 'Pear'] },
    { name: 'Papaya + apple', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Papaya', 'Apple'] },
    { name: 'Guava', type: 'veg', light: true, suits: ['K', 'P'], ing: ['Guava'] },
    { name: 'Banana + dates', type: 'veg', suits: ['V'], ing: ['Banana', 'Dates'] },
    { name: 'Sapota (chikoo)', type: 'veg', suits: ['V'], ing: ['Sapota'] },
  ]},
  { id: 'dinner', label: 'Dinner', time: '19:45', main: true, vegOnly: true, note: 'Lighter than lunch. No non-veg, no curd at night.', options: [
    { name: 'Phulka + moong dal + lauki sabzi + ghee', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Atta', 'Moong dal', 'Bottle gourd', 'Ghee'] },
    { name: 'Dal khichdi with ghee', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Rice', 'Moong dal', 'Ghee'] },
    { name: 'Rice + paneer sabzi + pumpkin curry', type: 'veg', suits: ['V', 'P'], ing: ['Rice', 'Paneer', 'Pumpkin', 'Ghee'] },
    { name: 'Ven pongal with ghee', type: 'veg', light: true, suits: ['V', 'K'], ing: ['Rice', 'Moong dal', 'Ghee', 'Pepper'] },
    { name: 'Phulka + palak paneer + ghee', type: 'veg', suits: ['V', 'P'], ing: ['Atta', 'Palak', 'Paneer', 'Ghee'] },
    { name: 'Barley khichdi with ghee', type: 'veg', light: true, suits: ['K', 'P'], ing: ['Barley', 'Moong dal', 'Ghee'] },
    { name: 'Ragi sangati + palak kootu', type: 'veg', suits: ['V', 'K'], ing: ['Ragi', 'Palak', 'Moong dal'] },
    { name: 'Vegetable dalia with ghee', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Dalia', 'Carrot', 'Beans', 'Ghee'] },
    { name: 'Jowar roti + mild bottle gourd curry', type: 'veg', suits: ['V', 'K'], ing: ['Jowar', 'Bottle gourd', 'Ghee'] },
    { name: 'Rice + ash gourd kootu + ghee', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Rice', 'Ash gourd', 'Moong dal', 'Coconut'] },
    { name: 'Phulka + methi dal + ghee', type: 'veg', suits: ['V', 'K'], ing: ['Atta', 'Methi', 'Toor dal', 'Ghee'] },
    { name: 'Rice + snake gourd poriyal + mild pepper rasam', type: 'veg', suits: ['V', 'K'], ing: ['Rice', 'Snake gourd', 'Tomato', 'Pepper'] },
    { name: 'Set dosa + ghee + coconut chutney', type: 'veg', suits: ['V', 'P'], ing: ['Idli rice', 'Urad dal', 'Coconut', 'Ghee'] },
    { name: 'Steamed idli + ghee', type: 'veg', light: true, suits: ['V', 'P', 'K'], ing: ['Idli rice', 'Urad dal', 'Ghee'] },
    { name: 'Chapati + mild yellow dal + cucumber slices', type: 'veg', light: true, suits: ['P', 'V'], ing: ['Atta', 'Toor dal', 'Cucumber'] },
  ]},
  { id: 'bed', label: 'Bedtime', time: '21:30', main: false, options: [
    { name: 'Warm milk with cardamom or turmeric', type: 'veg', light: true, suits: ['V', 'P'], ing: ['Milk', 'Cardamom', 'Turmeric'] },
    { name: 'Warm milk with dates', type: 'veg', suits: ['V'], ing: ['Milk', 'Dates'] },
    { name: 'Warm water + fennel seeds', type: 'veg', light: true, suits: ['P', 'K'], ing: ['Fennel'] },
    { name: 'Warm milk with crushed almonds', type: 'veg', suits: ['V', 'P'], ing: ['Milk', 'Almonds'] },
    { name: 'Small cup of very warm ginger water', type: 'veg', light: true, suits: ['K', 'V'], ing: ['Ginger'] },
  ]},
];

const CATEGORY = {
  'Grains & dals': ['Rice', 'Atta', 'Rava', 'Idli rice', 'Poha', 'Dalia', 'Oats', 'Toor dal', 'Moong dal', 'Whole moong', 'Urad dal', 'Chana dal', 'Roasted chana', 'Chickpeas', 'Peas'],
  'Millets': ['Ragi', 'Jowar', 'Bajra', 'Foxtail millet', 'Barley'],
  'Dairy & ghee': ['Ghee', 'Milk', 'Curd', 'Buttermilk', 'Paneer', 'Coconut milk'],
  'Leafy greens': ['Palak', 'Methi', 'Thotakura', 'Curry leaves', 'Coriander'],
  'Vegetables': ['Cucumber', 'Bottle gourd', 'Beans', 'Sweet potato', 'Ridge gourd', 'Pumpkin', 'Coconut', 'Ash gourd', 'Snake gourd', 'Carrot', 'Beetroot', 'Tomato', 'Raw banana', 'Potato', 'Cabbage', 'Onion', 'Corn'],
  'Fruit': ['Banana', 'Grapes', 'Papaya', 'Tender coconut', 'Mango', 'Pomegranate', 'Apple', 'Guava', 'Pear', 'Sweet lime', 'Sapota'],
  'Eggs, fish & meat': ['Eggs', 'Desi chicken', 'Broiler chicken', 'Rohu fish', 'Seer fish', 'Pomfret', 'Prawns', 'Mutton'],
  'Dry fruits, nuts & spices': ['Almonds', 'Cashews', 'Dates', 'Raisins', 'Makhana', 'Walnuts', 'Peanuts', 'Cardamom', 'Turmeric', 'Pepper', 'Cumin', 'Ginger', 'Fennel', 'Jaggery'],
};

// Eating-out guide by dosha and meal time
const EAT_OUT = {
  V: {
    breakfast: { label: 'Breakfast', safe: ['Idli with ghee and coconut chutney', 'Ven pongal with ghee', 'Rava upma (warm, soft)', 'Aloo or plain paratha with ghee', 'Poha with peanuts'], avoid: ['Dry crackers or biscuits breakfast', 'Salads and raw sprouts plates', 'Cold cereal with cold milk', 'Chilli-heavy bajji or vada'] },
    lunch: { label: 'Lunch', safe: ['South Indian veg meals (warm, ask mild)', 'Kerala chicken stew with appam', 'Mild egg curry with rice', 'Dal khichdi or pongal meals', 'Fish curry (mild) with rice'], avoid: ['Salad-only or raw food lunches', 'Cold sandwiches', 'Ice-cold drinks with the meal', 'Very dry fried items'] },
    snack: { label: 'Evening', safe: ['Warm badam milk', 'Dry fruit laddu', 'Roasted peanuts + jaggery', 'Kheer or payasam (small)', 'Banana + dates'], avoid: ['Iced coffee or cold drinks', 'Chips and dry namkeen', 'Raw salad snack plates', 'Skipping the snack entirely'] },
    dinner: { label: 'Dinner', safe: ['Dal khichdi with ghee', 'Idli + ghee + chutney', 'Phulka + mild dal + sabzi', 'Ven pongal', 'Rice + ash gourd kootu'], avoid: ['Any non-veg at night', 'Curd, raita or buttermilk', 'Salads and raw vegetables', 'Fried rice, noodles, manchurian'] },
  },
  P: {
    breakfast: { label: 'Breakfast', safe: ['Idli with ghee and coconut chutney', 'Ven pongal', 'Pesarattu or plain dosa', 'Rava upma', 'Boiled eggs with toast'], avoid: ['Masala dosa with spicy red chutney', 'Puri with spicy curry', 'Mirchi bajji or vada', 'Chilli idli'] },
    lunch: { label: 'Lunch', safe: ['South Indian veg meals (ask for less spicy)', 'Butter chicken or chicken korma with rice', 'Kerala chicken stew with appam', 'Mild egg curry with rice', 'Curd rice with pappu'], avoid: ['Andhra chicken fry or spicy gongura', 'Chilli chicken, chicken 65', 'Biryani with mirchi ka salan', 'Pickles and extra red chilli', 'Ice-cold soft drinks'] },
    snack: { label: 'Evening', safe: ['Fruit bowl', 'Tender coconut', 'Dry fruit laddu', 'Kheer or payasam (small)', 'Warm badam milk'], avoid: ['Samosa, pakodi, bajji', 'Pani puri and sour chaat', 'Iced coffee or cold drinks', 'Spicy mixture'] },
    dinner: { label: 'Dinner', safe: ['Dal khichdi with ghee', 'Phulka + dal + paneer butter masala (mild)', 'Ven pongal', 'Veg thali without curd', 'Moong dal + rice'], avoid: ['Any non-veg at night', 'Curd, raita or buttermilk', 'Fried rice, noodles, manchurian', 'Pizza, burgers, fried starters'] },
  },
  K: {
    breakfast: { label: 'Breakfast', safe: ['Pesarattu (no ghee overload)', 'Ragi dosa or foxtail upma', 'Idli with pepper + light chutney', 'Moong dal chilla', 'Steamed foods over fried'], avoid: ['Ghee-drenched anything in excess', 'Sweet porridge with sugar', 'Deep-fried vada or bajji', 'Creamy pastries and cakes'] },
    lunch: { label: 'Lunch', safe: ['Millet meals (jowar/ragi) with pappu', 'South Indian meals with more poriyal, less rice', 'Pepper chicken (not deep-fried)', 'Steamed fish with rice and dal', 'Kootu + poriyal combos'], avoid: ['Oily biryani and fried rice', 'Excess sweets with the meal', 'Heavy creamy curries', 'Ice cream or sweets right after'] },
    snack: { label: 'Evening', safe: ['Steamed corn with pepper', 'Sundal (boiled legumes)', 'Roasted chana', 'Spiced buttermilk (if morning snack)', 'Cucumber sticks with pepper'], avoid: ['Sweets and mithai boxes', 'Deep-fried snacks', 'Creamy milkshakes', 'Cheese-loaded snacks'] },
    dinner: { label: 'Dinner', safe: ['Barley khichdi or millet khichdi', 'Phulka + methi dal', 'Rice + snake gourd poriyal + pepper rasam', 'Steamed idli with pepper', 'Light vegetable soup (warm)'], avoid: ['Any non-veg at night', 'Curd, raita or buttermilk', 'Paneer-heavy dinners', 'Late-night snacking after dinner'] },
  },
};

// Short search word for each EAT_OUT "safe" dish, used for the Swiggy / Zomato
// buttons. null = not something you order from an app (no buttons shown).
const ORDER_SEARCH = {
  'Idli with ghee and coconut chutney': 'Idli', 'Ven pongal with ghee': 'Ven pongal', 'Rava upma (warm, soft)': 'Upma',
  'Aloo or plain paratha with ghee': 'Aloo paratha', 'Poha with peanuts': 'Poha',
  'South Indian veg meals (warm, ask mild)': 'South Indian meals', 'Kerala chicken stew with appam': 'Appam stew',
  'Mild egg curry with rice': 'Egg curry', 'Dal khichdi or pongal meals': 'Khichdi', 'Fish curry (mild) with rice': 'Fish curry',
  'Warm badam milk': 'Badam milk', 'Dry fruit laddu': 'Dry fruit laddu', 'Roasted peanuts + jaggery': 'Peanut chikki',
  'Kheer or payasam (small)': 'Payasam', 'Banana + dates': null,
  'Dal khichdi with ghee': 'Dal khichdi', 'Idli + ghee + chutney': 'Idli', 'Phulka + mild dal + sabzi': 'Phulka dal',
  'Ven pongal': 'Ven pongal', 'Rice + ash gourd kootu': 'Kootu',
  'Pesarattu or plain dosa': 'Pesarattu', 'Rava upma': 'Upma', 'Boiled eggs with toast': 'Boiled eggs',
  'South Indian veg meals (ask for less spicy)': 'South Indian meals', 'Butter chicken or chicken korma with rice': 'Chicken korma',
  'Curd rice with pappu': 'Curd rice', 'Fruit bowl': 'Fruit bowl', 'Tender coconut': 'Tender coconut',
  'Phulka + dal + paneer butter masala (mild)': 'Paneer butter masala', 'Veg thali without curd': 'Veg thali', 'Moong dal + rice': 'Dal rice',
  'Pesarattu (no ghee overload)': 'Pesarattu', 'Ragi dosa or foxtail upma': 'Ragi dosa', 'Idli with pepper + light chutney': 'Idli',
  'Moong dal chilla': 'Moong dal chilla', 'Steamed foods over fried': null,
  'Millet meals (jowar/ragi) with pappu': 'Millet meals', 'South Indian meals with more poriyal, less rice': 'South Indian meals',
  'Pepper chicken (not deep-fried)': 'Pepper chicken', 'Steamed fish with rice and dal': 'Steamed fish', 'Kootu + poriyal combos': 'Kootu',
  'Steamed corn with pepper': 'Sweet corn', 'Sundal (boiled legumes)': 'Sundal', 'Roasted chana': 'Roasted chana',
  'Spiced buttermilk (if morning snack)': 'Buttermilk', 'Cucumber sticks with pepper': null,
  'Barley khichdi or millet khichdi': 'Millet khichdi', 'Phulka + methi dal': 'Phulka dal',
  'Rice + snake gourd poriyal + pepper rasam': 'Rasam rice', 'Steamed idli with pepper': 'Idli', 'Light vegetable soup (warm)': 'Vegetable soup',
};

// What to type in the "note to restaurant" box when ordering online.
const ORDER_TIPS = {
  V: ['Ask for it hot and freshly made, with a little extra ghee.', 'Skip the cold drink or ice cream add-on.', 'Order soft, moist dishes over dry, crispy ones.'],
  P: ['Write "less spicy, no extra chilli" in the note to the restaurant.', 'Skip pickles, mirchi and sour chutneys on the side.', 'Pick coconut- or ghee-based gravies over red, oily ones.'],
  K: ['Write "less oil, less ghee" in the note to the restaurant.', 'Add a pepper rasam or soup instead of a sweet or dessert.', 'Order a smaller portion, or share one plate.'],
};

// Ready-to-paste "cooking instructions" for the restaurant, by constitution (TYPES key).
// Kept short so it fits the instructions box in ordering apps.
const ORDER_NOTES = {
  V: 'Please serve it hot and fresh. Mild spice. A little extra ghee is welcome. No raw onion.',
  P: 'Please make it less spicy, no extra chilli. Less oil. No pickle or raw onion on the side.',
  K: 'Please use less oil and ghee. Pepper and ginger are fine. No sweet or dessert add-on.',
  VP: 'Please make it mild, no extra chilli. Serve hot and fresh. A little ghee is fine.',
  PK: 'Please make it less spicy and less oily. No extra chilli, no pickle.',
  VK: 'Please serve it hot and fresh, with less oil. Pepper and ginger are fine.',
  VPK: 'Please make it mild, fresh and not too oily.',
};

// Zomato search pages need a city. Slugs as used in zomato.com URLs.
const ORDER_CITIES = [
  ['hyderabad', 'Hyderabad'], ['bangalore', 'Bengaluru'], ['chennai', 'Chennai'], ['vizag', 'Visakhapatnam'],
  ['vijayawada', 'Vijayawada'], ['mumbai', 'Mumbai'], ['ncr', 'Delhi NCR'], ['pune', 'Pune'], ['kolkata', 'Kolkata'],
  ['ahmedabad', 'Ahmedabad'], ['kochi', 'Kochi'], ['coimbatore', 'Coimbatore'],
];

const RULES = {
  all: [
    'Eat at the same times every day. Never skip a meal.',
    'No ice-cold drinks with meals. Warm or room-temperature water.',
    'Lunch should be your biggest meal; keep dinner light.',
    'If you eat non-veg, have it at lunch, not dinner.',
    'Curd only at lunch, never at night.',
    'Never mix milk with banana, sour fruit, or fish.',
    'Eat sitting, calmly, without screens when you can.',
  ],
  egg: [
    '1 to 2 eggs a day, boiled or poached.',
  ],
  V: [
    'Prefer warm, moist, well-cooked food — soupy dals, khichdi, ghee on rice.',
    'Keep raw salads, sprouts and dry crackers to a minimum.',
    'Sip warm water through the day, especially in the morning.',
    'Sweet, sour and salty tastes steady you — bitter and astringent dry you out.',
    'Exercise steady and regular, never to exhaustion.',
  ],
  P: [
    'Use ghee generously on rice, rotis and dal.',
    'Keep fried, spicy and sour food to a minimum.',
    'Cooling and sweet tastes suit you: coconut, cucumber, sweet fruits, milk.',
    'Skip the midday sun and hot kitchen hours; eat before you are famished.',
    'Avoid fermented, leftover and reheated foods when you can.',
  ],
  K: [
    'Prefer light, warm and dry foods — millets, barley, steamed dishes.',
    'Take a little less rice, sugar, ghee and dairy than you feel like.',
    'Pungent, bitter and astringent tastes wake up your digestion — pepper, ginger, greens.',
    'Move in the morning: a vigorous walk or workout lifts your whole day.',
    'Avoid heavy sweets, cheese and cold curd.',
  ],
};

const GOALS = {
  gain: {
    label: 'Gain weight',
    weekly: [0.25, 0.5],
    tips: {
      V: ['Warm khichdi, pongal and dal with ghee at every main meal.', 'Never skip meals; carry dates and nuts with you.', 'Sleep by 10 pm — rest builds the body.'],
      P: ['Rice with ghee, mild dal and sweet fruit keep you steady while gaining.', 'Milk with dates at bedtime adds nourishment.', 'Do not gain with fried food; gain with ghee, dal and milk.'],
      K: ['Gain with protein and dal more than sweets — your body holds weight easily.', 'Light strength meals: moong, paneer, eggs, chicken at lunch.', 'Keep moving even while gaining.'],
    },
    portion: 'Take one extra helping of the main dish, and add a spoon of ghee.',
    gym: 'Strength training 3-4 times a week with progressive load; keep rest days. Coconut water or dates + warm milk after. Over 60, pregnant, or new to exercise? Start with walking and check with your doctor.',
  },
  lose: {
    label: 'Lose weight',
    weekly: [-0.5, -0.25],
    tips: {
      V: ['Reduce portions gently, never crash — warm, soupy, smaller bowls.', 'Keep ghee (a spoon) so you do not get dry and anxious.', 'Eat slowly; stop at three-quarters full.'],
      P: ['Three good meals, no fried snacking — you do not need to skip food.', 'Sweet fruit instead of sweets; cool drinks over hot tea.', 'Do not get hungry-angry; plan meals ahead.'],
      K: ['Millets or barley instead of some rice; more poriyal, less dal ghee.', 'Breakfast light, no sweets between meals.', 'Warm water with ginger through the morning.'],
    },
    portion: 'Serve a little less rice; add more vegetables and keep protein steady.',
    note: 'Not suitable for under-18s or during pregnancy.',
    gym: 'Brisk walking daily plus strength training 2-3 times a week. Morning movement suits you best. Over 60, pregnant, or new to exercise? Start with walking and check with your doctor.',
  },
  maintain: {
    label: 'Maintain weight',
    weekly: [-0.2, 0.2],
    tips: {
      V: ['Regular meal times are your best friend — do not skip.', 'Keep warm, moist food and steady sleep.', 'Ghee and milk daily keep you grounded.'],
      P: ['Balanced meals with ghee, greens and sweet fruit keep you cool.', 'Avoid spicy and fried; eat before you are very hungry.', 'Easy walks after meals.'],
      K: ['Keep portion discipline — light dinner especially.', 'Millets, greens and pepper keep digestion bright.', 'Morning exercise keeps your steady strength.'],
    },
    portion: 'Eat to satisfaction, not fullness — leave a little space in the stomach.',
    gym: 'Any movement you enjoy 4-5 days a week: walking, yoga, gym, cycling. Over 60, pregnant, or new to exercise? Start with walking and check with your doctor.',
  },
};

const DAILY = [
  { text: 'Sip warm water through the morning.', for: ['V', 'K'] },
  { text: 'Eat lunch sitting down, without your phone.', for: ['all'] },
  { text: 'Add one spoon of ghee to your rice today.', for: ['V', 'P'] },
  { text: 'Take a short walk after lunch.', for: ['K', 'P'] },
  { text: 'Finish dinner at least two hours before bed.', for: ['all'] },
  { text: 'No curd or buttermilk at dinner tonight.', for: ['all'] },
  { text: 'Eat one sweet fruit instead of a sweet.', for: ['P', 'K'] },
  { text: 'Soak almonds tonight for tomorrow morning.', for: ['V', 'P'] },
  { text: 'Try one millet dish today — ragi or foxtail.', for: ['K'] },
  { text: 'Skip the cold drink; choose warm or room-temperature water.', for: ['V', 'P'] },
  { text: 'Add extra poriyal or greens to lunch.', for: ['K'] },
  { text: 'Chew each mouthful well — count to twenty.', for: ['K', 'V'] },
  { text: 'Eat at the same time as yesterday, as much as you can.', for: ['all'] },
  { text: 'Have a handful of nuts mid-morning.', for: ['V', 'P'] },
  { text: 'Keep pepper or ginger in today\'s cooking.', for: ['K', 'V'] },
  { text: 'Do ten minutes of easy stretching today.', for: ['V', 'K'] },
  { text: 'Skip fried snacks this evening.', for: ['P', 'K'] },
  { text: 'Drink tender coconut water today.', for: ['P', 'K'] },
  { text: 'Keep lunch bigger than dinner today.', for: ['K', 'V'] },
  { text: 'Go to bed by 10 pm tonight.', for: ['V', 'P'] },
  { text: 'Wake with the sun if you can tomorrow.', for: ['K', 'V'] },
  { text: 'Do not mix fruit with your meal; eat it alone.', for: ['all'] },
  { text: 'Take five slow breaths before your first bite.', for: ['V', 'P'] },
  { text: 'Add greens — palak, methi or thotakura — to a meal.', for: ['P', 'K'] },
  { text: 'If you eat non-veg today, keep it at lunch only.', for: ['all'] },
  { text: 'Have milk with cardamom at bedtime.', for: ['V', 'P'] },
  { text: 'Take the stairs or a short brisk walk today.', for: ['K'] },
  { text: 'Avoid reheated leftovers; cook fresh if possible.', for: ['P', 'V'] },
  { text: 'Eat a pomegranate or sweet lime today.', for: ['P'] },
  { text: 'Say thank you to your food before eating.', for: ['all'] },
  { text: 'Stop eating when you feel three-quarters full.', for: ['K', 'P'] },
  { text: 'Move a little every hour today — stand, stretch, walk.', for: ['K'] },
  { text: 'Plan tomorrow\'s breakfast tonight.', for: ['all'] },
];
