/* data-foods.js — FOODS library (PART 1: Rice, Millets & grains, Dals & legumes, Leafy greens, Vegetables)
   Ratings: V/P/K — 1 favour, 0 moderation, -1 reduce. Educational only. */
const FOODS = [

  // ---------- Rice ----------
  { id:'sona-masuri-rice', name:'Sona masuri rice', aka:['sona masoori','biyyam','chawal'], cat:'Rice', type:'veg', V:1, P:1, K:-1, why:'Sweet, soft and easy to digest; a touch heavy for Kapha — old rice or smaller portions work best.' },
  { id:'basmati-rice', name:'Basmati rice', aka:['basmathi','chinni biyyam'], cat:'Rice', type:'veg', V:1, P:1, K:0, why:'Light, slightly cooling and fragrant — friendly for Vata and Pitta; Kapha can enjoy modest portions.' },
  { id:'brown-rice', name:'Brown rice', aka:['unpolished rice','dampudu biyyam'], cat:'Rice', type:'veg', V:-1, P:0, K:0, why:'Fibre-rich but harder and drier — Vata tummies should cook it soft with ghee and warm spices.' },
  { id:'red-matta-rice', name:'Red matta rice', aka:['matta','kerala red rice','errabiyyam'], cat:'Rice', type:'veg', V:1, P:0, K:0, why:'Traditionally said to strengthen and nourish; heavier than white rice, so Kapha keeps portions moderate.' },
  { id:'black-rice', name:'Black rice', aka:['forbidden rice','kalo rice'], cat:'Rice', type:'veg', V:0, P:0, K:-1, why:'Rich, sweet and warming yet heavy — Kapha goes easy; nice soaked and cooked soft for others.' },
  { id:'old-rice', name:'Old rice (aged 1 year+)', aka:['puranam biyyam','purana chawal','old sona masuri'], cat:'Rice', type:'veg', V:1, P:1, K:0, why:'Classical texts praise aged rice as lighter and tridoshic — gentler on digestion than new-harvest rice.' },
  { id:'parboiled-rice', name:'Parboiled rice (udad / converted)', aka:['uppudu biyyam','parboiled chawal','sela rice'], cat:'Rice', type:'veg', V:1, P:0, K:0, why:'Steaming in the husk keeps nutrients in; nourishing for Vata, Kapha prefers smaller helpings.' },
  { id:'jeera-samba-rice', name:'Jeera samba rice', aka:['jeerasaga','seeraga samba','jheera rice'], cat:'Rice', type:'veg', V:1, P:1, K:0, why:'Tiny, aromatic and light on the stomach — good for Vata and Pitta; classic biryani rice of the south.' },
  { id:'poha-flattened-rice', name:'Poha (flattened rice)', aka:['atukulu','aval','chivda rice','flattened paddy'], cat:'Rice', type:'veg', V:1, P:0, K:0, why:'Light, quick-cooking and gentle; Vata loves it with a spoon of ghee, Kapha with lemon and less oil.' },

  // ---------- Millets & grains ----------
  { id:'ragi-finger-millet', name:'Ragi (finger millet)', aka:['ragulu','mandua','kelvargu','finger millet'], cat:'Millets & grains', type:'veg', V:1, P:0, K:0, why:'Calcium-rich and nourishing, classically said to strengthen bones; a bit heavy, so enjoy warm and fresh.' },
  { id:'jowar-sorghum', name:'Jowar (sorghum)', aka:['jonnalu','jowar','great millet','sorghum'], cat:'Millets & grains', type:'veg', V:0, P:1, K:1, why:'Cooling and light — good for summer heat and for Kapha; Vata should eat it warm with ghee.' },
  { id:'bajra-pearl-millet', name:'Bajra (pearl millet)', aka:['sajjalu','bajra','kambu','pearl millet'], cat:'Millets & grains', type:'veg', V:1, P:-1, K:1, why:'Warming and strengthening for winter and Vata; Pitta types should go easy, especially in hot weather.' },
  { id:'foxtail-millet', name:'Foxtail millet', aka:['korralu','kangni','thinai','foxtail'], cat:'Millets & grains', type:'veg', V:0, P:0, K:1, why:'Light and easy to digest, traditionally said to suit Kapha best; Vata enjoys it as warm porridge.' },
  { id:'little-millet', name:'Little millet', aka:['samalu','kutki','chama','samai'], cat:'Millets & grains', type:'veg', V:0, P:0, K:1, why:'Small-grained, light and non-heating — a gentle everyday millet; serve warm for Vata comfort.' },
  { id:'kodo-millet', name:'Kodo millet', aka:['arikelu','kodra','varagu'], cat:'Millets & grains', type:'veg', V:0, P:0, K:1, why:'Classically described as light and Kapha-friendly; cook soft with ghee so it does not dry Vata.' },
  { id:'barnyard-millet', name:'Barnyard millet', aka:['odalu','samwat ke chawal','kuthiravali'], cat:'Millets & grains', type:'veg', V:0, P:0, K:1, why:'Low and light, easy on the stomach — good for Kapha; Vata adds ghee and warm water alongside.' },
  { id:'barley', name:'Barley', aka:['yavam','jau','barli'], cat:'Millets & grains', type:'veg', V:-1, P:0, K:1, why:'Classical texts call barley light and Kapha-reducing; its dryness means Vata should keep portions small.' },
  { id:'wheat', name:'Wheat', aka:['godhuma','gehu','godi'], cat:'Millets & grains', type:'veg', V:1, P:0, K:-1, why:'Sweet, heavy and grounding — lovely for Vata; Kapha prefers chapatis over heavy wheat dishes.' },
  { id:'dalia-broken-wheat', name:'Dalia (broken wheat)', aka:['godhuma ravva','lapsi','broken wheat'], cat:'Millets & grains', type:'veg', V:1, P:0, K:0, why:'Soft upma or porridge that is gentle and warming — a nice light meal when digestion is dull.' },
  { id:'oats', name:'Oats', aka:['oats','oatmeal'], cat:'Millets & grains', type:'veg', V:1, P:0, K:-1, why:'Warm, soft and soothing for Vata; choose plain cooked oats, as Kapha finds the heavy versions too much.' },
  { id:'corn', name:'Corn (makka)', aka:['makkalu','makka','bhutta'], cat:'Millets & grains', type:'veg', V:0, P:0, K:1, why:'Light, dry and slightly sweet — Kapha-friendly; Vata should have it fresh-cooked, not as dry popcorn.' },

  // ---------- Dals & legumes ----------
  { id:'moong-whole', name:'Whole moong (green gram)', aka:['pesalu','moong sabut','pachha moong','green gram'], cat:'Dals & legumes', type:'veg', V:1, P:0, K:0, why:'Balanced and time-tested — one of the easiest beans; heavy eaters should keep the portion sensible.' },
  { id:'moong-dal-split', name:'Moong dal (split, yellow)', aka:['pesara pappu','moong ki dal','yellow moong dal'], cat:'Dals & legumes', type:'veg', V:1, P:1, K:0, why:'Light, sweet and cooling — the classical dal for weak digestion and for Pitta; tridoshic with ghee.' },
  { id:'moong-sprouts', name:'Sprouted moong', aka:['pesalu molakalu','moong ankurit','sprouts'], cat:'Dals & legumes', type:'veg', V:0, P:0, K:1, why:'Light and Kapha-friendly; raw sprouts can be rough on Vata — steam or lightly cook them.' },
  { id:'toor-dal', name:'Toor dal (pigeon pea)', aka:['kandipappu','toor ki dal','arhar dal','pigeon pea'], cat:'Dals & legumes', type:'veg', V:0, P:0, K:0, why:'The everyday dal — nourishing and fairly balanced; cook well and add ghee so it stays easy to digest.' },
  { id:'masoor-dal', name:'Masoor dal (red lentil)', aka:['misur pappu','masoor ki dal','lal masoor'], cat:'Dals & legumes', type:'veg', V:0, P:0, K:0, why:'Quick-cooking and gently warming; slightly heating, so Pitta keeps portions moderate with cooling sides.' },
  { id:'urad-dal-split', name:'Urad dal (black gram)', aka:['minapappu','urad ki dal','udad dal','black gram'], cat:'Dals & legumes', type:'veg', V:1, P:0, K:-1, why:'Heavy, unctuous and strengthening for Vata; Kapha and sluggish digestion should go easy on it.' },
  { id:'whole-urad', name:'Whole urad (black gram, skin on)', aka:['minumu','sabut urad','kali urad'], cat:'Dals & legumes', type:'veg', V:1, P:0, K:-1, why:'Very nourishing but the heaviest dal — best soaked overnight and spiced; Kapha takes small portions.' },
  { id:'chana-dal', name:'Chana dal (split Bengal gram)', aka:['shanaga pappu','chana ki dal','bengal gram dal'], cat:'Dals & legumes', type:'veg', V:0, P:0, K:1, why:'Sweet, slightly dry and Kapha-friendly when well cooked; can feel heavy, so eat warm with ghee.' },
  { id:'kabuli-chana', name:'Kabuli chana (chickpea)', aka:['chickpea','chole','senagalu','garbanzo'], cat:'Dals & legumes', type:'veg', V:-1, P:0, K:1, why:'Protein-rich but dry and gas-forming for Vata; soak well, cook soft and always add warming spices.' },
  { id:'horse-gram', name:'Horse gram (ulavalu)', aka:['ulavalu','kulthi','kollu','horsegram'], cat:'Dals & legumes', type:'veg', V:-1, P:-1, K:1, why:'Hot, dry and Kapha-cutting — a strong legume; Vata and Pitta should only take it in small amounts.' },
  { id:'rajma', name:'Rajma (kidney beans)', aka:['rajma','kidney beans'], cat:'Dals & legumes', type:'veg', V:-1, P:0, K:-1, why:'Heavy and gas-forming — soak overnight and cook thoroughly; light digestions should keep servings small.' },
  { id:'lobia', name:'Lobia (black-eyed peas)', aka:['alasandulu','lobia','chawli','black eyed pea'], cat:'Dals & legumes', type:'veg', V:0, P:0, K:0, why:'Moderately heavy but nourishing; soak well and spice gently — nice for strength when cooked soft.' },
  { id:'green-peas', name:'Green peas', aka:['batani','matar','green peas'], cat:'Dals & legumes', type:'veg', V:0, P:0, K:-1, why:'Sweet and a bit heavy — fine in moderation; Vata may notice gas, so cook with hing and cumin.' },
  { id:'moth-beans', name:'Moth beans (matki)', aka:['matki','turkish gram'], cat:'Dals & legumes', type:'veg', V:0, P:-1, K:1, why:'Light, dry and slightly heating — good for Kapha; Pitta and Vata should eat it cooked, not raw.' },

  // ---------- Leafy greens ----------
  { id:'palak-spinach', name:'Palak (spinach)', aka:['palakura','palak','spinach','paalak'], cat:'Leafy greens', type:'veg', V:0, P:0, K:1, why:'Sweet-bitter and nourishing; cook with ghee and a pinch of spice so Vata stays comfortable.' },
  { id:'methi-leaves', name:'Methi leaves (fenugreek greens)', aka:['menthikura','methi saag','fenugreek leaves','menthi'], cat:'Leafy greens', type:'veg', V:0, P:0, K:1, why:'Warming and bitter — good for Kapha; Pitta can enjoy it in moderation.' },
  { id:'thotakura', name:'Thotakura (amaranth greens)', aka:['amaranth leaves','thotakoora','chaulai saag','koyya thotakura'], cat:'Leafy greens', type:'veg', V:0, P:0, K:1, why:'Light and mineral-rich; slightly heating by nature, so Pitta keeps portions moderate.' },
  { id:'gongura', name:'Gongura (sorrel leaves)', aka:['gongura','ambadi','sorrel leaves','pulicha keerai'], cat:'Leafy greens', type:'veg', V:0, P:-1, K:1, why:'Tangy and heating — famous Andhra green; Pitta and acidity-prone stomachs should go easy.' },
  { id:'chukka-koora', name:'Chukka koora (green sorrel)', aka:['chukka koora','khatti bhaji','green sorrel','khatta palak'], cat:'Leafy greens', type:'veg', V:0, P:-1, K:1, why:'Sour and Kapha-friendly; the tang can stir heat, so Pitta enjoys only a little.' },
  { id:'curry-leaves', name:'Curry leaves', aka:['karivepaku','kadi patta','karivepila','curry leaf'], cat:'Leafy greens', type:'veg', V:1, P:0, K:0, why:'Classically said to kindle digestion and calm Vata; chew a few daily — old wisdom in a tiny leaf.' },
  { id:'coriander-leaves', name:'Coriander leaves', aka:['kothimeera','dhaniya patta','cilantro','kothimir'], cat:'Leafy greens', type:'veg', V:1, P:1, K:0, why:'Cooling and gentle — a traditional soother for excess heat; sprinkle generously on dal and rasam.' },
  { id:'mint-leaves', name:'Mint leaves (pudina)', aka:['pudina','pudhina','mint','phudina'], cat:'Leafy greens', type:'veg', V:0, P:1, K:1, why:'Cooling yet digestive — lovely in chutney or warm water; take with warm foods so Vata is not chilled.' },
  { id:'moringa-leaves', name:'Moringa leaves (drumstick tree)', aka:['munaga aaku','moringa patta','drumstick leaves','sahjan'], cat:'Leafy greens', type:'veg', V:0, P:0, K:1, why:'Nutrient-dense and warming — Kapha-friendly in moderation; too much may stir heat or dryness.' },
  { id:'drumstick-tree-leaves', name:'Drumstick leaves (murungai keerai)', aka:['murungai keerai','munaga aku','moringa keerai'], cat:'Leafy greens', type:'veg', V:0, P:0, K:1, why:'Iron-rich village green; light and warming — good weekly, not daily, for Pitta-leaning folks.' },
  { id:'ponnaganti-koora', name:'Ponnaganti koora', aka:['ponnaganti koora','ponnanganni','maticook','joyweed greens'], cat:'Leafy greens', type:'veg', V:0, P:1, K:1, why:'Cooling and traditionally valued for the eyes; light and easy — cook simply with garlic and pepper.' },
  { id:'bachali-koora', name:'Bachali koora (Malabar spinach)', aka:['bachali koora','poi saag','basella','malabar spinach'], cat:'Leafy greens', type:'veg', V:1, P:1, K:0, why:'Soft, slippery and cooling — soothing for Vata and Pitta; quite moist, so Kapha keeps it occasional.' },

  // ---------- Vegetables ----------
  { id:'lauki-bottle-gourd', name:'Lauki (bottle gourd)', aka:['sorakaya','lauki','dudhi','bottle gourd','anapakaya'], cat:'Vegetables', type:'veg', V:1, P:1, K:0, why:'Cooling, watery and very easy to digest — a classical favourite for Pitta; light when cooked simple.' },
  { id:'ridge-gourd', name:'Ridge gourd (beerakaya)', aka:['beerakaya','turai','peerkangai','ridge gourd'], cat:'Vegetables', type:'veg', V:0, P:1, K:0, why:'Slightly bitter, cooling and gentle — good in dal; mild enough for nearly everyone when fresh.' },
  { id:'snake-gourd', name:'Snake gourd (potlakaya)', aka:['potlakaya','padwal','chichinda','snake gourd'], cat:'Vegetables', type:'veg', V:0, P:1, K:1, why:'Light, cooling and Kapha-friendly — a mild gourd best cooked with cumin and pepper.' },
  { id:'ash-gourd', name:'Ash gourd (boodida gummadikaya)', aka:['boodida gummadikaya','petha','ash gourd','pooshanikai'], cat:'Vegetables', type:'veg', V:1, P:1, K:0, why:'Classically praised as cooling and sattvic; its moisture makes Kapha keep portions small.' },
  { id:'pumpkin', name:'Pumpkin (gummadikaya)', aka:['gummadikaya','kaddu','poosanikai','yellow pumpkin'], cat:'Vegetables', type:'veg', V:0, P:1, K:0, why:'Sweet, soft and gently cooling — a friendly gourd for most; slightly heavy, so Kapha eats modestly.' },
  { id:'bitter-gourd', name:'Bitter gourd (kakarakaya)', aka:['kakarakaya','karela','paavakkai','bitter melon'], cat:'Vegetables', type:'veg', V:-1, P:1, K:1, why:'Bitter taste cuts Kapha and clears heat, classically; Vata finds it drying — cook with oil and coconut.' },
  { id:'drumstick-pods', name:'Drumstick pods (munagakaya)', aka:['munagakaya','seeng','murungakkai','drumstick','sahjan pods'], cat:'Vegetables', type:'veg', V:0, P:0, K:1, why:'Warming and nourishing in sambar; slightly heating and heavy — Pitta and Kapha keep it moderate.' },
  { id:'okra', name:'Okra (bhendi / bendakaya)', aka:['bendakaya','bhindi','vendakkai','okra','ladies finger'], cat:'Vegetables', type:'veg', V:1, P:0, K:0, why:'Its gentle sliminess soothes Vata digestion; fry lightly so it does not become too oily for Kapha.' },
  { id:'brinjal', name:'Brinjal (eggplant)', aka:['vankaya','baingan','kathirikai','eggplant','brinjal'], cat:'Vegetables', type:'veg', V:-1, P:-1, K:1, why:'Classically heating and slightly gas-forming — Pitta and Vata go easy; Kapha tolerates it best.' },
  { id:'tomato', name:'Tomato', aka:['tamata','tamatar','thakkali','tomato'], cat:'Vegetables', type:'veg', V:0, P:-1, K:1, why:'Sour and a little heating — fine cooked in dal, but Pitta with heat symptoms should not overdo raw ones.' },
  { id:'carrot', name:'Carrot', aka:['gajar','carrot','orange carrot'], cat:'Vegetables', type:'veg', V:1, P:0, K:0, why:'Sweet, grounding and easy when cooked; nourishing for Vata, and Kapha simply watches portions.' },
  { id:'beetroot', name:'Beetroot', aka:['beetroot','chukandar','beet'], cat:'Vegetables', type:'veg', V:1, P:0, K:-1, why:'Sweet, heavy and blood-nourishing by tradition; slightly Kapha-increasing — enjoy cooked, not raw-heavy.' },
  { id:'french-beans', name:'Beans (French beans)', aka:['beans','french beans','pharasbean'], cat:'Vegetables', type:'veg', V:0, P:0, K:1, why:'Light and Kapha-friendly when steamed; cook with hing so Vata avoids bloating.' },
  { id:'cabbage', name:'Cabbage', aka:['gobhi','patta gobi','cabbage'], cat:'Vegetables', type:'veg', V:-1, P:0, K:1, why:'Light and Kapha-reducing, but gas-forming — Vata should cook it well with cumin and ghee.' },
  { id:'cauliflower', name:'Cauliflower', aka:['cauliflower','phool gobhi','gobi','kovi'], cat:'Vegetables', type:'veg', V:-1, P:0, K:0, why:'Slightly dry and gas-forming; steam well with warming spices — light digestions keep portions small.' },
  { id:'potato', name:'Potato', aka:['aloo','bangaladumpa','batata','potato'], cat:'Vegetables', type:'veg', V:0, P:0, K:-1, why:'Sweet, heavy and Vata-grounding when baked or boiled; Kapha avoids oily fries and big servings.' },
  { id:'sweet-potato', name:'Sweet potato', aka:['chilagadadumpa','shakarkandi','sweet potato','genasu'], cat:'Vegetables', type:'veg', V:1, P:0, K:-1, why:'Sweet, warm and nourishing — lovely baked with ghee; heavy for Kapha, so keep portions modest.' },
  { id:'raw-banana', name:'Raw banana (plantain)', aka:['aratikaya','kaccha kela','raw plantain','vazhakkai'], cat:'Vegetables', type:'veg', V:0, P:0, K:1, why:'Astringent, dry and Kapha-friendly; can feel heavy for Vata — cook soft with coconut or ghee.' },
  { id:'cucumber', name:'Cucumber', aka:['kheera','cucumber','southekayi','keera'], cat:'Vegetables', type:'veg', V:0, P:1, K:0, why:'Cooling and hydrating — lovely in summer; Vata takes it with meals rather than alone.' },
  { id:'onion', name:'Onion', aka:['ullipaya','pyaz','vengayam','onion'], cat:'Vegetables', type:'veg', V:1, P:0, K:1, why:'Warming and digestive, good for Vata; heating by nature, so Pitta keeps fried and raw onion light.' },
  { id:'garlic', name:'Garlic', aka:['velluli','lahsun','poondu','garlic'], cat:'Vegetables', type:'veg', V:1, P:-1, K:1, why:'Strongly heating — classically used to cut Kapha and warm Vata; Pitta should use it sparingly.' },
  { id:'radish', name:'Radish (mullangi)', aka:['mullangi','mooli','mullangi','daikon','radish'], cat:'Vegetables', type:'veg', V:0, P:-1, K:1, why:'Pungent and Kapha-cutting; heating for Pitta, and avoid taking milk right after radish.' },
  { id:'ivy-gourd', name:'Ivy gourd (dondakaya)', aka:['dondakaya','tendli','kovakkai','ivy gourd'], cat:'Vegetables', type:'veg', V:0, P:0, K:1, why:'Light, mild and Kapha-friendly; cook with a little oil and cumin so Vata stays settled.' },
  { id:'cluster-beans', name:'Cluster beans (goruchikkudu)', aka:['goruchikkudu','gawar phali','kothavarangai','cluster beans'], cat:'Vegetables', type:'veg', V:-1, P:0, K:1, why:'Astringent and light — good for Kapha; can bloat Vata, so cook soft with coconut and hing.' },
  { id:'colocasia', name:'Colocasia (arbi)', aka:['chamadumpa','arbi','seppankilangu','taro'], cat:'Vegetables', type:'veg', V:0, P:0, K:-1, why:'Starchy and heavy but soothing when well cooked; Kapha goes easy — always cook it fully.' },
  { id:'elephant-yam', name:'Elephant foot yam (suran)', aka:['kanda','suran','senai kizhangu','elephant yam'], cat:'Vegetables', type:'veg', V:0, P:0, K:1, why:'Warming, filling and Kapha-friendly; slightly itchy unless cooked well with tamarind and turmeric.' },

  // ---------- Fruits ----------
  { id:'banana-fruit', name:'Banana', aka:['arati pandu','kela','vazhai pazham','banana'], cat:'Fruits', type:'veg', V:1, P:0, K:0, why:'Sweet, grounding and quick energy for Vata; slightly heavy and mucus-forming, so Kapha goes easy.' },
  { id:'mango-ripe', name:'Mango (ripe)', aka:['mamidi pandu','aam','mangai','ripe mango'], cat:'Fruits', type:'veg', V:1, P:0, K:0, why:'Sweet, warming and nourishing — the king of fruits; enjoy ripe in season, not with milk or curd.' },
  { id:'papaya', name:'Papaya', aka:['boppayi'], cat:'Fruits', type:'veg', V:1, P:-1, K:0, why:'Sweet and heating in potency — good for Vata digestion; Pitta types keep it small, especially in summer.' },
  { id:'pomegranate', name:'Pomegranate', aka:['danimma','anaar','madhulai','pomegranate'], cat:'Fruits', type:'veg', V:1, P:1, K:0, why:'Sweet-astringent and classically praised for all types — gentle, cooling and kind to digestion.' },
  { id:'grapes', name:'Grapes', aka:['draksha','angoor','grapes'], cat:'Fruits', type:'veg', V:1, P:1, K:0, why:'Sweet, moist and cooling — classical texts value grapes as nourishing; Kapha keeps portions small.' },
  { id:'apple', name:'Apple', aka:['seb','apple'], cat:'Fruits', type:'veg', V:0, P:1, K:0, why:'Sweet-astringent and cooling when sweet — stewed apples are gentler for Vata than cold raw ones.' },
  { id:'pear', name:'Pear', aka:['nashpati'], cat:'Fruits', type:'veg', V:0, P:1, K:0, why:'Juicy, sweet and cooling — fine for Pitta; slightly rough for Vata, so eat ripe and at room temperature.' },
  { id:'guava', name:'Guava', aka:['jama','amrood','guava'], cat:'Fruits', type:'veg', V:0, P:0, K:1, why:'Sweet-astringent and light — Kapha-friendly; Vata eats it ripe and soft, not unripe and hard.' },
  { id:'sapota-chikoo', name:'Sapota (chikoo)', aka:['sapota','chikoo','sapodilla'], cat:'Fruits', type:'veg', V:1, P:0, K:-1, why:'Sweet, heavy and grounding for Vata; quite rich and Kapha-increasing — a small one is enough.' },
  { id:'jackfruit', name:'Jackfruit', aka:['panasa','kathal','pala pazham','jackfruit'], cat:'Fruits', type:'veg', V:0, P:-1, K:-1, why:'Sweet, heavy and heating — filling but hard to digest; eat a few pieces warm and not with other sweets.' },
  { id:'watermelon', name:'Watermelon', aka:['puchakaya'], cat:'Fruits', type:'veg', V:0, P:1, K:0, why:'Cooling and hydrating in summer; eat alone, at room temperature, so digestion is not chilled.' },
  { id:'musk-melon', name:'Musk melon', aka:['kharbooja','madhuranam','muskmelon','cantaloupe'], cat:'Fruits', type:'veg', V:0, P:1, K:0, why:'Sweet, juicy and cooling — a gentle summer fruit; eat fresh and alone, not straight from the fridge.' },
  { id:'orange', name:'Orange', aka:['kamala pandu','santra','orange'], cat:'Fruits', type:'veg', V:0, P:0, K:0, why:'Sweet-sour and light — Kapha-friendly in season; sourness means Pitta keeps it moderate.' },
  { id:'lemon', name:'Lemon', aka:['nimma','nimbu','elumichai','lemon'], cat:'Fruits', type:'veg', V:0, P:0, K:1, why:'Sour yet classically digestive — a squeeze on dal helps all types; Pitta avoids excess sour juice.' },
  { id:'amla', name:'Amla (Indian gooseberry)', aka:['usiri','amla','nellikai','gooseberry'], cat:'Fruits', type:'veg', V:1, P:1, K:1, why:'Classically prized as tridoshic — sour-astringent and cooling; a daily tradition in many homes.' },
  { id:'dates-fruit', name:'Dates', aka:['kharjura','khajur','dates'], cat:'Fruits', type:'veg', V:1, P:0, K:0, why:'Sweet, warm and strength-giving — lovely with warm milk at night; heavy, so a few suffice.' },
  { id:'figs', name:'Figs', aka:['anzi','anjeer','figs'], cat:'Fruits', type:'veg', V:1, P:0, K:0, why:'Sweet, nourishing and traditionally said to help regularity; soaked figs are gentler than dry ones.' },
  { id:'tender-coconut', name:'Tender coconut', aka:['kobbari neellu','nariyal pani','ilaneer','tender coconut water'], cat:'Fruits', type:'veg', V:1, P:1, K:0, why:'Cooling, sweet and naturally hydrating — classical summer drink; best taken fresh, not chilled.' },
  { id:'pineapple', name:'Pineapple', aka:['anasa','anannas','pineapple'], cat:'Fruits', type:'veg', V:0, P:-1, K:0, why:'Sweet-sour and mildly heating — Kapha enjoys it; Pitta and acidic stomachs should keep it small.' },
  { id:'custard-apple', name:'Custard apple (sitaphal)', aka:['seethaphalam','sitaphal','custard apple','sharifa'], cat:'Fruits', type:'veg', V:1, P:0, K:-1, why:'Sweet, creamy and grounding for Vata; heavy and rich, so Kapha keeps it an occasional treat.' },
  { id:'jamun', name:'Jamun', aka:['neredu','jamun','naval pazham','java plum'], cat:'Fruits', type:'veg', V:0, P:1, K:1, why:'Astringent-sour and cooling — a short-season classic; astringency means Vata eats just a few.' },

  // ---------- Dairy ----------
  { id:'milk', name:'Milk', aka:['paalu','doodh','milk','cow milk'], cat:'Dairy', type:'veg', V:1, P:1, K:0, why:'Classically nourishing and calming for Vata — take it warm with spices, alone, never with sour fruit.' },
  { id:'curd', name:'Curd (yogurt)', aka:['perugu','dahi','thayir','curd','yogurt'], cat:'Dairy', type:'veg', V:0, P:-1, K:-1, why:'Sour, heavy and heating — best at midday with a pinch of salt or sugar; traditionally avoided at night.' },
  { id:'paneer', name:'Paneer', aka:['paneer','chenna','cottage cheese'], cat:'Dairy', type:'veg', V:0, P:1, K:-1, why:'Sweet, cooling and protein-rich — good for Pitta when fresh, unsalted and mildly spiced; heavy for Kapha, so keep portions small.' },
  { id:'butter', name:'Butter', aka:['venna','makhan','butter'], cat:'Dairy', type:'veg', V:1, P:0, K:-1, why:'Sweet and unctuous — lovely on warm rotis for Vata; heavy, so Kapha keeps it to a thin spread.' },

  // ---------- Oils & ghee ----------
  { id:'ghee', name:'Ghee', aka:['neyyi','ghrit','ghee','clarified butter'], cat:'Oils & ghee', type:'veg', V:1, P:1, K:0, why:'Classically called the best of fats — kindles digestion and calms both Vata and Pitta when fresh.' },
  { id:'sesame-oil', name:'Sesame oil (gingelly)', aka:['nuvvula noone','til ka tel','nallennai','sesame oil'], cat:'Oils & ghee', type:'veg', V:1, P:-1, K:0, why:'Warming and strengthening, the classic southern cooking oil; heating, so Pitta uses it lightly.' },
  { id:'coconut-oil', name:'Coconut oil', aka:['kobbari noone','nariyal tel','coconut oil'], cat:'Oils & ghee', type:'veg', V:0, P:1, K:-1, why:'Sweet and cooling — good for Pitta cooking; heavy and Kapha-raising, so use a modest spoon.' },
  { id:'groundnut-oil', name:'Groundnut oil', aka:['verusenaga noone','moongphali tel','peanut oil'], cat:'Oils & ghee', type:'veg', V:0, P:0, K:0, why:'Balanced everyday oil with gentle warmth — suits most types when used fresh and not re-heated.' },
  { id:'mustard-oil', name:'Mustard oil', aka:['aavalanune','sarson ka tel','mustard oil','kachi ghani'], cat:'Oils & ghee', type:'veg', V:1, P:-1, K:1, why:'Pungent and warming — cuts Kapha and warms Vata; its sharp heat means Pitta avoids it.' },
  { id:'sunflower-oil', name:'Sunflower oil', aka:['suryamukhi tel','sunflower oil'], cat:'Oils & ghee', type:'veg', V:0, P:1, K:0, why:'Light and neutral to mildly cooling — a gentle everyday choice for Pitta; use fresh, not reused.' },

  // ---------- Eggs ----------
  { id:'whole-egg', name:'Whole egg', aka:['kodi guddu','anda','egg','whole egg'], cat:'Eggs', type:'egg', V:1, P:0, K:0, why:'Warm, nourishing and strengthening — classically heavy yet grounding; eat well-cooked with pepper.' },
  { id:'egg-white', name:'Egg white', aka:['white','albumen','egg white'], cat:'Eggs', type:'egg', V:0, P:0, K:0, why:'Light protein without the yolk fat — easier for Kapha; slightly drying, so pair with moist foods.' },

  // ---------- Fish & seafood ----------
  { id:'rohu-fish', name:'Rohu', aka:['rohu','bocha chepa','rohu fish'], cat:'Fish & seafood', type:'nonveg', V:1, P:0, K:0, why:'Freshwater fish, warming and nourishing — classically easier on digestion than many sea fish.' },
  { id:'katla-fish', name:'Katla', aka:['katla','katla chepa','catla'], cat:'Fish & seafood', type:'nonveg', V:1, P:0, K:0, why:'Sweet, heavy and strengthening — good for Vata when fresh; grill or curry lightly spiced.' },
  { id:'seer-fish', name:'Seer fish (vanjaram)', aka:['vanjaram','surmai','seer fish','king fish'], cat:'Fish & seafood', type:'nonveg', V:1, P:0, K:0, why:'Firm, meaty and nourishing — coastal favourite; best fresh-grilled with pepper rather than deep-fried.' },
  { id:'pomfret', name:'Pomfret', aka:['chanduva','paplet','pomfret'], cat:'Fish & seafood', type:'nonveg', V:1, P:0, K:0, why:'Light, sweet and easy to digest among sea fish — gentle nourishment when simply cooked.' },
  { id:'sardine-fish', name:'Sardine (mathi)', aka:['mathi','chala','sardine','pilchard'], cat:'Fish & seafood', type:'nonveg', V:1, P:0, K:0, why:'Small, oily and warming — traditionally strengthening; eat fresh, as sardines spoil faster than big fish.' },
  { id:'mackerel-fish', name:'Mackerel (bangda)', aka:['bangda','bangda chepa','mackerel','aiyla'], cat:'Fish & seafood', type:'nonveg', V:1, P:0, K:0, why:'Oily, warming and Kapha-friendly when spiced; always eat it very fresh and well cooked.' },
  { id:'tilapia-fish', name:'Tilapia', aka:['tilapia','jilebi chepa'], cat:'Fish & seafood', type:'nonveg', V:0, P:0, K:0, why:'Mild, light and easy to digest — a balanced everyday fish when cooked with ginger and pepper.' },
  { id:'prawns', name:'Prawns', aka:['royyalu','jhinga','shrimp','prawns','chemmeen'], cat:'Fish & seafood', type:'nonveg', V:0, P:-1, K:-1, why:'Classically heavy and heating — tasty but tricky; eat fresh, well spiced, and not with curd.' },
  { id:'crab', name:'Crab', aka:['peetha','khekda','crab','nandu'], cat:'Fish & seafood', type:'nonveg', V:0, P:-1, K:0, why:'Sweet-heavy and traditionally considered heating — an occasional treat; skip when digestion is weak.' },
  { id:'dried-fish', name:'Dried fish', aka:['sukha machli','karuvadu','dried fish'], cat:'Fish & seafood', type:'nonveg', V:0, P:-1, K:1, why:'Salty, heating and Kapha-cutting — traditional coastal fare; Pitta and high-BP folks go easy.' },

  // ---------- Meat & poultry ----------
  { id:'desi-chicken', name:'Desi chicken (country)', aka:['naatu kodi','desi murgi','country chicken'], cat:'Meat & poultry', type:'nonveg', V:1, P:0, K:0, why:'Classically considered lighter and more strengthening than broiler — good nourishment in moderation.' },
  { id:'broiler-chicken', name:'Broiler chicken', aka:['broiler','chicken','murgi'], cat:'Meat & poultry', type:'nonveg', V:0, P:0, K:0, why:'Widely available and moderate — choose fresh, well-cooked preparations over deep-fried ones.' },
  { id:'mutton-goat', name:'Mutton (goat)', aka:['mamsam','mutton','bakre ka meat','goat meat'], cat:'Meat & poultry', type:'nonveg', V:1, P:0, K:0, why:'Classically strengthening and warming for Vata — heavy, so eat moderate portions with ginger and pepper.' },
  { id:'lamb', name:'Lamb', aka:['lamb','gorre mamsam'], cat:'Meat & poultry', type:'nonveg', V:1, P:0, K:0, why:'Warm and nourishing like goat but fattier — enjoy slow-cooked with warming spices in winter.' },
  { id:'liver-organ-meat', name:'Liver / organ meat', aka:['kaleji','yakrut','liver','organ meat'], cat:'Meat & poultry', type:'nonveg', V:1, P:-1, K:0, why:'Rich, heating and deeply nourishing — traditionally occasional; heavy and Pitta-stirring.' },
  { id:'pork', name:'Pork', aka:['pandu mamsam','pig meat','pork'], cat:'Meat & poultry', type:'nonveg', V:0, P:-1, K:-1, why:'Classically heavy, oily and heating — the hardest meat to digest; keep portions small and rare.' },

  // ---------- Nuts & seeds ----------
  { id:'almonds', name:'Almonds', aka:['badam','badam pappu','almonds'], cat:'Nuts & seeds', type:'veg', V:1, P:0, K:0, why:'Sweet, warming and strength-giving — soaked and peeled is the classical way; a handful is enough.' },
  { id:'cashews', name:'Cashews', aka:['jeedipappu','kaju','cashew'], cat:'Nuts & seeds', type:'veg', V:1, P:0, K:-1, why:'Sweet, creamy and grounding — nourishing for Vata; heavy, so Kapha keeps it to a few.' },
  { id:'walnuts', name:'Walnuts', aka:['akhrot','walnuts','akroot'], cat:'Nuts & seeds', type:'veg', V:1, P:0, K:0, why:'Warm, oily and brain-nourishing by tradition — good for Vata; a small daily handful suits most.' },
  { id:'pistachio', name:'Pistachio', aka:['pista','pistachio'], cat:'Nuts & seeds', type:'veg', V:0, P:0, K:0, why:'Sweet and gently warming — a balanced nut; salted versions make Kapha and BP-watchers cautious.' },
  { id:'peanuts', name:'Peanuts', aka:['verusenaga pappu','moongphali','groundnut','peanuts'], cat:'Nuts & seeds', type:'veg', V:0, P:0, K:0, why:'Warming, heavy and satisfying — fine in moderation; can be gas-forming, so roast and chew well.' },
  { id:'sesame-seeds', name:'Sesame seeds', aka:['nuvvulu','til','sesame','ellu'], cat:'Nuts & seeds', type:'veg', V:1, P:-1, K:0, why:'Warm, oily and classically strengthening for Vata in winter; heating, so Pitta takes them sparingly.' },
  { id:'flax-seeds', name:'Flax seeds', aka:['flaxseed','alsi','flax seeds'], cat:'Nuts & seeds', type:'veg', V:0, P:0, K:1, why:'Oily yet light — grind fresh and take with warm water; gentle and Kapha-friendly in small doses.' },
  { id:'pumpkin-seeds', name:'Pumpkin seeds', aka:['gummadikaya bijam','kaddu ke beej','pumpkin seeds'], cat:'Nuts & seeds', type:'veg', V:0, P:0, K:1, why:'Sweet, nutty and light — a gentle seed for all types; roast lightly and chew well.' },
  { id:'sunflower-seeds', name:'Sunflower seeds', aka:['suryamukhi bijalu','sunflower seeds'], cat:'Nuts & seeds', type:'veg', V:0, P:1, K:1, why:'Light and mildly cooling — good for Pitta; sprinkle on warm dishes rather than eating handfuls dry.' },
  { id:'coconut-fresh', name:'Coconut (fresh)', aka:['kobbari','nariyal','thengai','fresh coconut'], cat:'Nuts & seeds', type:'veg', V:1, P:1, K:-1, why:'Sweet, cooling and grounding — classic in southern cooking; heavy, so Kapha grates lightly.' },
  { id:'makhana', name:'Makhana (fox nuts)', aka:['makhana','fox nuts','phool makhana','gorgon nut'], cat:'Nuts & seeds', type:'veg', V:1, P:1, K:0, why:'Light, sweet and classically sattvic — easy to digest and gentle for all types when roasted.' },
  { id:'raisins', name:'Raisins', aka:['draksha endu','kishmish','raisins'], cat:'Nuts & seeds', type:'veg', V:1, P:0, K:0, why:'Sweet, moist and gently nourishing — soaked raisins are the classical way; Kapha eats a few.' },

  // ---------- Spices & herbs ----------
  { id:'turmeric', name:'Turmeric', aka:['pasupu','haldi','manjal','turmeric'], cat:'Spices & herbs', type:'veg', V:0, P:0, K:0, why:'Bitter, warming and classically tridoshic in cooking amounts — the golden root of every Indian kitchen.' },
  { id:'cumin', name:'Cumin', aka:['jeelakarra','jeera','seeragam','cumin'], cat:'Spices & herbs', type:'veg', V:1, P:0, K:1, why:'Classically digestive and Vata-calming — a pinch in almost everything helps kindle the appetite.' },
  { id:'coriander-seed', name:'Coriander seed', aka:['dhaniyalu','dhania','kothamalli vidhai','coriander seeds'], cat:'Spices & herbs', type:'veg', V:1, P:1, K:1, why:'Cooling yet digestive — tridoshic and classical for soothing excess heat in rasam and dal water.' },
  { id:'fennel', name:'Fennel', aka:['sompalu','saunf','perunjeeragam','fennel'], cat:'Spices & herbs', type:'veg', V:1, P:1, K:1, why:'Sweet, cooling and classically digestive — chew a pinch after meals to freshen and settle.' },
  { id:'cardamom', name:'Cardamom', aka:['yelakula','elaichi','elakkai','cardamom'], cat:'Spices & herbs', type:'veg', V:0, P:1, K:1, why:'Sweet, gently warming and classically tridoshic — lovely in milk, payasam and coffee.' },
  { id:'fresh-ginger', name:'Fresh ginger', aka:['allam','adrak','inji','ginger'], cat:'Spices & herbs', type:'veg', V:1, P:0, K:1, why:'Classically called universal spice in cooking — warms Vata and cuts Kapha; Pitta uses it mildly.' },
  { id:'dry-ginger', name:'Dry ginger (sonth)', aka:['sonth','chukku','sunthi','dry ginger'], cat:'Spices & herbs', type:'veg', V:1, P:-1, K:1, why:'More concentrated and heating than fresh — excellent for Vata and Kapha; Pitta takes only a pinch.' },
  { id:'black-pepper', name:'Black pepper', aka:['miriyalu','kali mirch','milagu','pepper'], cat:'Spices & herbs', type:'veg', V:1, P:0, K:1, why:'Pungent and warming — classically kindles digestion and clears Kapha; Pitta keeps it moderate.' },
  { id:'red-chilli', name:'Red chilli', aka:['yendu mirapakayalu','lal mirch','red chili','red chilli'], cat:'Spices & herbs', type:'veg', V:0, P:-1, K:1, why:'Sharp and very heating — cuts Kapha but easily stirs Pitta and acidity; cook with restraint.' },
  { id:'green-chilli', name:'Green chilli', aka:['mirchi'], cat:'Spices & herbs', type:'veg', V:0, P:-1, K:1, why:'Hot and pungent — a little wakes up dull digestion; too much stirs heat, especially for Pitta.' },
  { id:'mustard-seed', name:'Mustard seed', aka:['aavalu','rai','kadugu','mustard seeds'], cat:'Spices & herbs', type:'veg', V:1, P:-1, K:1, why:'Pungent and warming — the southern tadka; heating, so Pitta keeps the tempering light.' },
  { id:'hing', name:'Hing (asafoetida)', aka:['inguva','hing','perungayam','asafoetida'], cat:'Spices & herbs', type:'veg', V:1, P:0, K:1, why:'Classically anti-flatulent — a pinch in dal and beans keeps Vata comfortable without heat.' },
  { id:'cinnamon', name:'Cinnamon', aka:['dalchina chekka','dalchini','pattai','cinnamon'], cat:'Spices & herbs', type:'veg', V:1, P:0, K:1, why:'Sweet-pungent and warming — traditionally said to kindle digestion; lovely in winter drinks.' },
  { id:'clove', name:'Clove', aka:['lavangam','laung','grambu','clove'], cat:'Spices & herbs', type:'veg', V:1, P:-1, K:1, why:'Strongly warming and aromatic — clears Kapha and warms Vata; Pitta uses one, not many.' },
  { id:'fenugreek-seed', name:'Fenugreek seed', aka:['menthulu','methi dana','venthayam','fenugreek seeds'], cat:'Spices & herbs', type:'veg', V:1, P:-1, K:1, why:'Bitter and warming — balances taste in sambar and pickles; use in small pinches.' },
  { id:'ajwain', name:'Ajwain (carom seed)', aka:['oma','vaamu','ajwain','carom seeds'], cat:'Spices & herbs', type:'veg', V:1, P:-1, K:1, why:'Pungent and warming — a classic for Vata gas and heaviness; Pitta takes only a pinch.' },
  { id:'tamarind', name:'Tamarind', aka:['chintapandu','imli','puli','tamarind'], cat:'Spices & herbs', type:'veg', V:1, P:-1, K:0, why:'Sour and classically Kapha-cutting — the soul of southern curries; Pitta keeps the tang gentle.' },
  { id:'saffron', name:'Saffron', aka:['kunkuma puvvu','kesar','saffron'], cat:'Spices & herbs', type:'veg', V:1, P:1, K:1, why:'Classically tridoshic and sattvic — a few strands in warm milk are a treasured tradition.' },

  // ---------- Sweeteners ----------
  { id:'jaggery', name:'Jaggery', aka:['bellam','gud','vellam','jaggery'], cat:'Sweeteners', type:'veg', V:0, P:0, K:-1, why:'Sweet and warming with minerals — classically gentler than sugar; heavy, so Kapha goes easy.' },
  { id:'honey', name:'Honey', aka:['thene'], cat:'Sweeteners', type:'veg', V:0, P:0, K:1, why:'Sweet, astringent and Kapha-cutting — always raw, never heated. Never for babies under 1 year.' },
  { id:'white-sugar', name:'White sugar', aka:['chekara','cheeni','sugar'], cat:'Sweeteners', type:'veg', V:0, P:0, K:-1, why:'Sweet but classically considered empty and Kapha-increasing — keep it small and occasional.' },
  { id:'mishri', name:'Mishri (rock sugar)', aka:['patika bellam','kalkandam','rock sugar'], cat:'Sweeteners', type:'veg', V:1, P:1, K:0, why:'Classically cooling and gentler than white sugar — traditionally soothing for the throat.' },
  { id:'palm-jaggery', name:'Palm jaggery', aka:['thati bellam','gur','karupatti','palm jaggery'], cat:'Sweeteners', type:'veg', V:0, P:0, K:-1, why:'Mineral-rich and less cloying than sugar — a traditional sweetener; still sweet, so Kapha moderates.' },

  // ---------- Drinks ----------
  { id:'coconut-water', name:'Coconut water', aka:['kobbari neellu','nariyal pani'], cat:'Drinks', type:'veg', V:1, P:1, K:0, why:'Naturally sweet and cooling — classical summer refresher; drink fresh, not chilled.' },
  { id:'tea', name:'Tea (chai)', aka:['chai','tea','tea powder'], cat:'Drinks', type:'veg', V:0, P:-1, K:0, why:'Warming but stimulating and astringent — okay in the morning; Pitta and insomnia-prone folks go light.' },
  { id:'coffee', name:'Coffee', aka:['kaapi','coffee','kapi'], cat:'Drinks', type:'veg', V:0, P:-1, K:0, why:'Hot, bitter and stimulating — classically Rajasic; one morning cup is enough, none after sunset.' },
  { id:'buttermilk', name:'Buttermilk (chaas / majjiga)', aka:['majjiga','chaas','mor','buttermilk','sambharam'], cat:'Drinks', type:'veg', V:0, P:1, K:1, why:'Classically praised as light and digestive — with ginger and curry leaves it suits lunch perfectly.' },
  { id:'warm-water', name:'Warm water', aka:['vedi neellu','garam pani','warm water'], cat:'Drinks', type:'veg', V:1, P:1, K:1, why:'The simplest classical habit — sipped warm through the day, it gently supports digestion for all.' },
  { id:'cold-iced-drinks', name:'Cold / iced drinks', aka:['cold drinks','soda','iced beverages'], cat:'Drinks', type:'veg', V:-1, P:-1, K:-1, why:'Classically said to snuff out digestive fire — icy drinks with meals unsettle every type.' },
  { id:'fresh-fruit-juice', name:'Fresh fruit juice', aka:['juice','pandu rasam','fresh juice'], cat:'Drinks', type:'veg', V:0, P:0, K:-1, why:'Fresh-squeezed and at room temperature is fine occasionally; whole fruit is the better classical habit.' },
  { id:'alcohol', name:'Alcohol', aka:['madhyam','sharab','alcohol','wine'], cat:'Drinks', type:'veg', V:-1, P:-1, K:-1, why:'Classically heating, drying and agitating to all doshas — Ayurveda advises keeping it rare or none.' }
];

const CAT_ICON = { 'Rice':'fRice', 'Millets & grains':'fMillet', 'Dals & legumes':'fDal', 'Leafy greens':'fLeafy', 'Vegetables':'fVeg', 'Fruits':'fFruit', 'Nuts & seeds':'fNuts', 'Dairy':'fDairy', 'Oils & ghee':'fGhee', 'Spices & herbs':'fSpice', 'Sweeteners':'fSweet', 'Drinks':'fDrink', 'Eggs':'fEgg', 'Fish & seafood':'fFish', 'Meat & poultry':'fMeat' };
function iconFor(food) { if (!food) return null; if (food.icon) return food.icon; if (/coconut/.test(food.id)) return 'fCoconut'; return CAT_ICON[food.cat] || null; }
function findFood(name) { // match an ingredient/meal word to a FOODS item by exact name, then aka, then name-contains; case-insensitive
  const n = String(name || '').toLowerCase().trim(); if (!n) return null;
  return FOODS.find((f) => f.name.toLowerCase() === n) || FOODS.find((f) => (f.aka || []).some((a) => a.toLowerCase() === n)) || FOODS.find((f) => f.name.toLowerCase().includes(n) || n.includes(f.name.toLowerCase().replace(/\s*\(.*\)/, ''))) || null; }
function ficoHtml(key) { return key && typeof ART !== 'undefined' && ART[key] ? '<span class="fico" aria-hidden="true">' + ART[key] + '</span>' : ''; }

